
export const certification = [
  { value: 0, label: 'Organic' },
  { value: 1, label: 'Fair Trade' },
  { value: 2, label: 'None' }
];

export const roastProfiles = [
  { value: 0, label: 'Light' },
  { value: 1, label: 'Medium' },
  { value: 2, label: 'Dark' },
  { value: 3, label: 'Espresso' },
  { value: 4, label: 'Cold Brew' }
];

export const cupping1 = [
  { value: 0, label: 'Roasted' },
  { value: 1, label: 'Spices' },
  { value: 2, label: 'Nutty Cocoa' },
  { value: 3, label: 'Sweet' },
  { value: 4, label: 'Floral' },
  { value: 5, label: 'Fruity' },
  { value: 6, label: 'Sour Fermented' },
  { value: 7, label: 'Green Vegetative' },
  { value: 8, label: 'Other' }
];

export const cupping2 = [
  { value: 0, label: 'Pipe Tobacco' },
  { value: 1, label: 'Tobacco' },
  { value: 2, label: 'Burnt' },
  { value: 3, label: 'Cereal' },
  { value: 4, label: 'Pungent' },
  { value: 5, label: 'Pepper' },
  { value: 6, label: 'Brown Spice' },
  { value: 7, label: 'Nutty' },
  { value: 8, label: 'Cocoa' },
  { value: 9, label: 'Brown Sugar' },
  { value: 10, label: 'Vanillin' },
  { value: 11, label: 'Overall Sweet' },
  { value: 12, label: 'Sweet Aromatics' },
  { value: 13, label: 'Black Tea' },
  { value: 14, label: 'Floral' },
  { value: 15, label: 'Berry' },
  { value: 16, label: 'Dried Fruit' },
  { value: 17, label: 'Other Fruit' },
  { value: 18, label: 'Citrus Fruit' },
  { value: 19, label: 'Sour' },
  { value: 20, label: 'Alcohol Fermented' },
  { value: 21, label: 'Olive Oil' },
  { value: 22, label: 'Raw' },
  { value: 23, label: 'Green Vegetative' },
  { value: 24, label: 'Beany' },
  { value: 25, label: 'Papery Musty' },
  { value: 26, label: 'Chemical' }
];

export const cupping3 = [
  { value: 0, label: 'Acrid' },
  { value: 1, label: 'Ashy' },
  { value: 2, label: 'Smoky' },
  { value: 3, label: 'Brown Roast' },
  { value: 4, label: 'Grain' },
  { value: 5, label: 'Malt' },
  { value: 6, label: 'Anise' },
  { value: 7, label: 'Nutmeg' },
  { value: 8, label: 'Cinnamon' },
  { value: 9, label: 'Clove' },
  { value: 10, label: 'Peanuts' },
  { value: 11, label: 'Hazelnut' },
  { value: 12, label: 'Almond' },
  { value: 13, label: 'Chocolate' },
  { value: 14, label: 'Dark Chocolate' },
  { value: 15, label: 'Molasses' },
  { value: 16, label: 'Maple Syrup' },
  { value: 17, label: 'Caramelized' },
  { value: 18, label: 'Honey' },
  { value: 19, label: 'Chamomile' },
  { value: 20, label: 'Rose' },
  { value: 21, label: 'Jasmine' },
  { value: 22, label: 'Blackberry' },
  { value: 23, label: 'Raspberry' },
  { value: 24, label: 'Blackberry' },
  { value: 25, label: 'Strawberry' },
  { value: 26, label: 'Raisin' },
  { value: 27, label: 'Prune' },
  { value: 28, label: 'Coconut' },
  { value: 29, label: 'Cherry' },
  { value: 30, label: 'Pomegranate' },
  { value: 31, label: 'Pineapple' },
  { value: 32, label: 'Grape' },
  { value: 33, label: 'Apple' },
  { value: 34, label: 'Peach' },
  { value: 35, label: 'Pear' },
  { value: 36, label: 'Grapefruit' },
  { value: 37, label: 'Orange' },
  { value: 38, label: 'Lemon' },
  { value: 39, label: 'Lime' },
  { value: 40, label: 'Sour Aromatics' },
  { value: 41, label: 'Acetic Acid' },
  { value: 42, label: 'Butyric Acid' },
  { value: 43, label: 'Isovaleric Acid' },
  { value: 44, label: 'Citric Acid' },
  { value: 45, label: 'Malic Acid' },
  { value: 46, label: 'Winey' },
  { value: 47, label: 'Whiskey' },
  { value: 48, label: 'Fermented' },
  { value: 49, label: 'Overripe' },
  { value: 50, label: 'Underripe' },
  { value: 51, label: 'Peapod' },
  { value: 52, label: 'Fresh' },
  { value: 53, label: 'Dark Green' },
  { value: 54, label: 'Vegetative' },
  { value: 55, label: 'Hay Like' },
  { value: 56, label: 'Herb Like' },
  { value: 57, label: 'Stale' },
  { value: 58, label: 'Cardboard' },
  { value: 59, label: 'Papery' },
  { value: 60, label: 'Woody' },
  { value: 61, label: 'Moldy Damp' },
  { value: 62, label: 'Musty Dusty' },
  { value: 63, label: 'Musty Earthy' },
  { value: 64, label: 'Animalic' },
  { value: 65, label: 'Meaty Brothy' },
  { value: 66, label: 'Phenolic' },
  { value: 67, label: 'Bitter' },
  { value: 68, label: 'Salty' },
  { value: 69, label: 'Medicinal' },
  { value: 70, label: 'Petroleum' },
  { value: 71, label: 'Skunky' },
  { value: 72, label: 'Rubber' }
];

export const process = [
  { value: 0, label: 'Washed' },
  { value: 1, label: 'Semi-washed' },
  { value: 2, label: 'Pulp natural' },
  { value: 3, label: 'Natural' },
  { value: 4, label: 'Honey' },
  { value: 5, label: 'White honey' },
  { value: 6, label: 'Yellow honey' },
  { value: 7, label: 'Red honey' },
  { value: 8, label: 'Black honey' }
];

export const variety = [
  { value: 0, label: 'Bourbon' },
  { value: 1, label: 'Orange Bourbon' },
  { value: 2, label: 'Red Bourbon' },
  { value: 3, label: 'Yellow Bourbon' },
  { value: 4, label: 'Purple Bourbon' },
  { value: 5, label: 'Caturra' },
  { value: 6, label: 'Yellow Caturra' },
  { value: 7, label: 'Cataui' },
  { value: 8, label: 'Yellow Cataui' },
  { value: 9, label: 'Orange Cataui' },
  { value: 10, label: 'Icatu' },
  { value: 11, label: 'Mondo Nuovo' },
  { value: 12, label: 'Colombia' },
  { value: 13, label: 'Castillo' },
  { value: 14, label: 'Ethiopia Heirloom' },
  { value: 15, label: 'Djember' },
  { value: 16, label: 'Gesha' },
  { value: 17, label: 'Pacamara' },
  { value: 18, label: 'Maragogype' },
  { value: 19, label: 'Javanica' },
  { value: 20, label: 'Sidra' },
  { value: 21, label: 'Java' },
  { value: 22, label: 'Maracaturra' },
  { value: 23, label: 'Elefante' },
  { value: 24, label: 'SL28' },
  { value: 25, label: 'SL34' },
  { value: 26, label: 'Ruiru 11' },
  { value: 27, label: 'Villalobos' },
  { value: 28, label: 'Tekisic' },
  { value: 29, label: 'Typica' },
  { value: 30, label: 'Villa Sarchi' },
  { value: 31, label: 'Mokka' },
  { value: 32, label: 'Pacas' },
  { value: 33, label: 'Pache' },
  { value: 34, label: 'Lempira' },
  { value: 35, label: 'Batian' },
  { value: 36, label: 'Marabourbon' }
];
