version: 0.2

env:
  variables:
    INTEGRATION_DIR: "/tmp/nodeapp"

phases:
  install:
    runtime-versions:
        nodejs: 8
  build:
    commands:
      - mkdir -p ${INTEGRATION_DIR}
      - yarn install
      - export REACT_APP_BW_API_URL=${BW_API_URL}
      - export REACT_APP_MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - export REACT_APP_CRYPTOJS_SECRET_KEY=${CRYPTOJS_SECRET_KEY}
      - yarn run build
      - CI=true yarn test
      - cp -r build/* ${INTEGRATION_DIR}

artifacts:
  files:
    - '**/*'
  name: admin-dashboard-${DEPLOY_ENV}-$(date +%Y-%m-%d) 
  base-directory: '/tmp/nodeapp'
